# Generated by Django 4.1.2 on 2022-10-22 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0005_alter_pet_slug'),
    ]

    operations = [
      ]
