# Generated by Django 4.1.2 on 2022-10-30 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_collection_app', '0002_car_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2049, ('Year must be between 1980 and 2049',)), django.core.validators.MinValueValidator(1980, ('Year must be between 1980 and 2049',))]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2, ('The username must be a minimum of 2 chars',))]),
        ),
    ]
